In [11]:
train_df = pd.read_csv("annotated_meddialog.csv")

train_df.head()

,patient_message,doctor_response,dialogue_context,intent
0,"What causes azoospermia ?\n\nHello Doctor, I a...","Hi,As you got complete absence of sperms in th...",NaN,Symptom
1,Which treatment is advisable for rheumatic art...,hi in case of RA tell me what is your diet...,NaN,Appointment
2,Is painful blister rash related to shingles or...,"Hello, It seems to be shingles most likely. I ...",NaN,Symptom
3,13 year old with hives and swelling. Allergic ...,It takes 3-4 wek to wash out the eefect of dru...,NaN,Symptom
4,Q. Can Yasmin birth control pill be used as an...,"Hi. How are you doing? Yes, as you have heard,...",NaN,Symptom

In [1]:
import pandas as pd
import re
from datasets import load_dataset

# Load dataset
dataset = load_dataset("OpenMed/MedDialog")

train_df = dataset["train"].to_pandas()

# Remove duplicates
train_df = train_df.drop_duplicates().reset_index(drop=True)

train_df.shape

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

(218697, 3)

In [2]:
train_df = train_df[["patient_message"]]

train_df.head()

                                     patient_message
0  What causes azoospermia ?\n\nHello Doctor, I a...
1  Which treatment is advisable for rheumatic art...
2  Is painful blister rash related to shingles or...
3  13 year old with hives and swelling. Allergic ...
4  Q. Can Yasmin birth control pill be used as an...

In [3]:
train_df["clean_text"] = train_df["patient_message"]

In [4]:
train_df["clean_text"] = train_df["clean_text"].str.lower()

In [5]:
# Remove newline, carriage return and tab characters
train_df["clean_text"] = train_df["clean_text"].str.replace(r"[\n\r\t]", " ", regex=True)

train_df[["patient_message", "clean_text"]].head(3)

,patient_message,clean_text
0,"What causes azoospermia ?\n\nHello Doctor, I a...","what causes azoospermia ? hello doctor, i am ..."
1,Which treatment is advisable for rheumatic art...,which treatment is advisable for rheumatic art...
2,Is painful blister rash related to shingles or...,is painful blister rash related to shingles or...

In [6]:
# Remove email addresses
train_df["clean_text"] = train_df["clean_text"].str.replace(
    r"\S+@\S+", " ", regex=True
)

# Remove phone numbers (10 or more digits)
train_df["clean_text"] = train_df["clean_text"].str.replace(
    r"\b\d{10,}\b", " ", regex=True
)

# Remove URLs
train_df["clean_text"] = train_df["clean_text"].str.replace(
    r"http\S+|www\S+", " ", regex=True
)

train_df[["patient_message", "clean_text"]].head(5)

,patient_message,clean_text
0,"What causes azoospermia ?\n\nHello Doctor, I a...","what causes azoospermia ? hello doctor, i am ..."
1,Which treatment is advisable for rheumatic art...,which treatment is advisable for rheumatic art...
2,Is painful blister rash related to shingles or...,is painful blister rash related to shingles or...
3,13 year old with hives and swelling. Allergic ...,13 year old with hives and swelling. allergic ...
4,Q. Can Yasmin birth control pill be used as an...,q. can yasmin birth control pill be used as an...

In [7]:
# Keep only letters, numbers and spaces
train_df["clean_text"] = train_df["clean_text"].str.replace(
    r"[^a-z0-9\s]",
    " ",
    regex=True
)

train_df[["patient_message", "clean_text"]].head(5)

,patient_message,clean_text
0,"What causes azoospermia ?\n\nHello Doctor, I a...",what causes azoospermia hello doctor i am ...
1,Which treatment is advisable for rheumatic art...,which treatment is advisable for rheumatic art...
2,Is painful blister rash related to shingles or...,is painful blister rash related to shingles or...
3,13 year old with hives and swelling. Allergic ...,13 year old with hives and swelling allergic ...
4,Q. Can Yasmin birth control pill be used as an...,q can yasmin birth control pill be used as an...

In [8]:
# Replace multiple spaces with a single space
train_df["clean_text"] = train_df["clean_text"].str.replace(
    r"\s+",
    " ",
    regex=True
).str.strip()

train_df[["patient_message", "clean_text"]].head(5)

,patient_message,clean_text
0,"What causes azoospermia ?\n\nHello Doctor, I a...",what causes azoospermia hello doctor i am 30 y...
1,Which treatment is advisable for rheumatic art...,which treatment is advisable for rheumatic art...
2,Is painful blister rash related to shingles or...,is painful blister rash related to shingles or...
3,13 year old with hives and swelling. Allergic ...,13 year old with hives and swelling allergic t...
4,Q. Can Yasmin birth control pill be used as an...,q can yasmin birth control pill be used as an ...

In [9]:
train_df[["patient_message", "clean_text"]].head(3)

,patient_message,clean_text
0,"What causes azoospermia ?\n\nHello Doctor, I a...",what causes azoospermia hello doctor i am 30 y...
1,Which treatment is advisable for rheumatic art...,which treatment is advisable for rheumatic art...
2,Is painful blister rash related to shingles or...,is painful blister rash related to shingles or...

In [13]:
train_df.columns

Index(['patient_message', 'doctor_response', 'dialogue_context', 'intent'], dtype='object')

In [14]:
import re

# Create editable copy
train_df["clean_text"] = train_df["patient_message"]

# Lowercase
train_df["clean_text"] = train_df["clean_text"].str.lower()

# Remove newlines
train_df["clean_text"] = train_df["clean_text"].str.replace(r"[\n\r\t]", " ", regex=True)

# Remove emails
train_df["clean_text"] = train_df["clean_text"].str.replace(r"\S+@\S+", " ", regex=True)

# Remove phone numbers
train_df["clean_text"] = train_df["clean_text"].str.replace(r"\b\d{10,}\b", " ", regex=True)

# Remove URLs
train_df["clean_text"] = train_df["clean_text"].str.replace(r"http\S+|www\S+", " ", regex=True)

# Remove punctuation
train_df["clean_text"] = train_df["clean_text"].str.replace(r"[^a-z0-9\s]", " ", regex=True)

# Remove extra spaces
train_df["clean_text"] = train_df["clean_text"].str.replace(r"\s+", " ", regex=True).str.strip()

In [15]:
processed_df = train_df[["clean_text", "intent"]]

processed_df.head()

                                          clean_text       intent
0  what causes azoospermia hello doctor i am 30 y...      Symptom
1  which treatment is advisable for rheumatic art...  Appointment
2  is painful blister rash related to shingles or...      Symptom
3  13 year old with hives and swelling allergic t...      Symptom
4  q can yasmin birth control pill be used as an ...      Symptom

In [16]:
processed_df.to_csv("processed_meddialog.csv", index=False)

print(processed_df.shape)

(218697, 2)